---
## These are just examples - replace with your tasks
- name: Debug
  ansible.builtin.debug:
    var: ludus_dns_server

- name: Message
  ansible.builtin.debug:
    msg: Put your ansible tasks here

- name: General purpose caching downloader example (Windows)
  ansible.builtin.include_tasks:
    file: download_file.yml
  vars:
    ludus_download_file_name: adkwinpesetup.exe
    ludus_download_file_url: https://download.microsoft.com/download/0/1/C/01CC78AA-B53B-4884-B7EA-74F2878AA79F/adk/adksetup.exe
    ludus_download_file_host_path: "C:\\ludus\\sccm"
    # Only use checksums for files that do not update!
    ludus_download_file_checksum: "sha256:666c4b0813e80ff52b564b4d261e26d1e6e48023164a26a684bff24d12dc2a78"

- name: General purpose caching downloader example (Linux)
  ansible.builtin.include_tasks:
    file: download_file.yml
  vars:
    ludus_download_file_name: elastic-agent-8.13.1-linux-x86_64.tar.gz
    ludus_download_file_url: https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.13.1-linux-x86_64.tar.gz
    ludus_download_file_host_path: /opt/elastic
    # Only use checksums for files that do not update!
    ludus_download_file_checksum: "sha512:a91a09124eacfdce9cb8d6876ae2896ad0f0682ca8e112ccf2ec5660f3ec4db96b230869f5dc5011136a15d2882a58b71e45775843f31c282ee8c8db9524a27f"
## Replace above with your tasks
