- name: Ensure the shares path exists
  ansible.windows.win_file:
    path: "{{ share.path }}"
    state: directory
  loop: "{{ win_shares }}"
  loop_control:
    loop_var: share
  when: ansible_system == 'Win32NT'

- name: Create Windows shares
  ansible.windows.win_share:
    caching_mode: "{{ share.caching_mode | default(omit)  }}"
    change: "{{ share.change | default(omit) }}"
    deny: "{{ share.deny | default(omit) }}"
    description: "{{ share.description | default(omit) }}"
    encrypt: "{{ share.encrypt | default(omit) }}"
    full: "{{ share.full | default(omit) }}"
    list: "{{ share.list | default(omit) }}"
    name: "{{ share.name }}"
    path: "{{ share.path }}"
    rule_action: "{{ share.rule_action | default(omit) }}"
    scope_name: "{{ share.scope_name  | default(omit) }}"
    state: "{{ share.state | default(omit) }}"
  loop: "{{ win_shares }}"
  loop_control:
    loop_var: share
  when: "ansible_system == 'Win32NT'"
